---
  parserOptions:
    ecmaVersion: 8
  env:
    node: true
    mocha: true
    es6: true
  extends: 'eslint:recommended'
  rules:
    quotes: [2, 'single']
    semi: [2, 'always']
    no-fallthrough: 2
    no-redeclare: 2
    no-self-assign: 2
    spaced-comment: 
      - 2
      - always
    no-trailing-spaces: 2
    no-var: 2
    prefer-const: 2
    indent:
      - 2
      - 2
      - VariableDeclarator:
          let: 2
          const: 3
        SwitchCase: 1
