language: node_js
node_js:
  - 8
env:
  - NODE_ENV=test CXX="g++-4.8" CC="gcc-4.8"
services:
  - mysql
sudo: required
dist: trusty
before_script:
  - cp ./config/secret/sample.js ./config/secret/test.js
  - NODE_ENV=test npm run init-db-standalone
script:
  - npm run lint
  #- npm run test-once
